# Mapping of page IDs to their respective modules and classes.

PAGE_MAPPING = {
    40: ("src.ui.pages.dashboard_page", "DashboardPage", "dashboard_page", None),
    60: ("src.ui.pages.automotive_stock_page", "AutomotiveStockPage", "automotive_stock_page", None),
    10: ("src.ui.pages.personnel_page", "PersonnelPage", "personnel_page", None),
    30: ("src.ui.pages.appointments_page", "AppointmentsPage", "appointments_page", None),
    101: ("src.ui.pages.accounting_page", "AccountingPage", "accounting_page", None),
    105: ("src.ui.pages.finance.bank_page", "BankPage", "bank_page", None),
    106: ("src.ui.pages.finance.check_note_page", "CheckNotePage", "check_note_page", None),
    115: ("src.ui.pages.invoice_page", "InvoiceCreationPage", "invoice_page", None),
    130: ("src.ui.pages.settings_page", "SettingsPage", "settings_page", None),
    70: ("src.ui.pages.support_page", "SupportPage", "support_page", None),
    135: ("src.ui.pages.audit_log_page", "AuditLogPage", "audit_log_page", None),
    180: ("src.ui.pages.backup_page", "BackupPage", "backup_page", None),
    261: ("src.ui.pages.user_manual_page", "UserManualPage", "user_manual_page", None),
    140: ("src.ui.pages.services_page", "ServicesPage", "services_page", None),
    41: ("src.ui.pages.service_board_page", "ServiceBoardPage", "service_board_page", None),
    42: ("src.ui.pages.job_service_tracking_page", "JobServiceTrackingPage", "service_list_page", None),
    50: ("src.ui.pages.technical_stock_page", "TechnicalStockPage", "stock_page", None),
    51: (
        "src.ui.pages.stock_locations_page",
        "StockLocationsPage",
        "stock_locations_page",
        None,
    ),
    145: ("src.ui.pages.brands_page", "BrandsPage", "brands_page", None),
    146: (
        "src.ui.pages.product_groups_page",
        "ProductGroupsPage",
        "product_groups_page",
        None,
    ),
    147: (
        "src.ui.pages.report_templates_page",
        "ReportTemplatesPage",
        "report_templates_page",
        None,
    ),
    65: ("src.ui.pages.external_tracking_page", "ExternalTrackingPage", "external_tracking_page", None),
    66: ("src.ui.pages.loaner_devices_page", "LoanerDevicesPage", "loaner_page", None),
    201: ("src.ui.pages.job_service_tracking_page", "JobServiceTrackingPage", "job_service_tracking_page", None),
    210: ("src.ui.pages.vehicle_maintenance_page", "VehicleMaintenancePage", "vehicle_maintenance_page", None),
    150: ("src.ui.pages.sales_hub_page", "SalesHubPage", "sales_hub_page", None),
    21: ("src.ui.pages.customers_page", "CustomersPage", "customers_page", None),
    26: ("src.ui.pages.customers_page_parts", "PartnersPage", "partners_page", None),
    25: ("src.ui.pages.contracts_page", "ContractsPage", "contracts_page", None),
    90: ("src.ui.pages.reminders_page", "RemindersPage", "reminders_page", None),
    160: ("src.ui.pages.knowledge_base_page", "KnowledgeBasePage", "kb_page", None),
    170: ("src.ui.pages.ai_assistant_page", "AIAssistantPage", "ai_assistant_page", None),
    120: ("src.ui.pages.announcements_page", "AnnouncementsPage", "announcements_page", None),
    61: ("src.ui.pages.field_service_page", "FieldServicePage", "field_service_page", None),
    200: ("src.ui.pages.project_management.projects_page", "ProjectsPage", "projects_page", None),
    202: ("src.ui.pages.project_management.project_archive_page", "ProjectArchivePage", "project_archive_page", None),
    250: ("src.ui.pages.mobile_guide_page", "MobileGuidePage", "mobile_guide_page", None),
    300: ("src.ui.pages.sales_hub_page", "SalesHubPCBuilderPage", "sales_hub_pc_builder_page", None),
    313: ("src.ui.pages.offer_pages", "OffersPage", "offers_page", None),
    314: ("src.ui.pages.offer_pages", "OfferReportsPage", "offer_reports_page", None),
}

PAGE_NAMES = {
    40: "Genel Bakış",
    41: "Servis Panosu",
    42: "Servis Listesi",
    62: "Teknisyen Paneli",
    60: "Araç Parça Stoğu",
    61: "Saha Servis Haritası",
    30: "Randevular",
    150: "Teklif Olu\u015ftur",
    21: "Müşteri Listesi",
    26: "Çalışma Ortaklarımız",
    25: "Bakım Sözleşmeleri",
    90: "Hatırlatıcılar",
    50: "Stok Yönetimi",
    140: "Hizmet Tanımları",
    101: "Gelir / Gider Takibi",
    105: "Banka Hesapları",
    106: "Çek / Senet Takibi",
    115: "E-Fatura Oluştur",
    170: "AI Asistan",
    160: "Bilgi Bankası",
    130: "Sistem Ayarları",
    135: "Log Kayıtları",
    180: "Yedekleme Merkezi",
    70: "Destek Merkezi",
    10: "Personel Yönetimi",
    120: "Duyurular",
    65: "Lojistik & Garanti Yönetimi",
    200: "Proje Yönetimi",
    201: "İş / Servis Takibi Raporları",
    202: "Proje Arşivi",
    210: "Araç Bakım Takibi",
    145: "Cihaz Bilgisi & Markalar",
    146: "\u00dcr\u00fcn Grubu Y\u00f6netimi",
    147: "Rapor C\u00fcmle Kal\u0131plar\u0131",
    66: "Emanet Konsinye Cihazlar",
    250: "Mobil Teknik Kılavuz",
    300: "PC Yapılandırıcı",
    261: "Kullanım Kılavuzu",
    313: "T\u00fcm Teklifler",
    314: "Teklif Raporlar\u0131",
}

GROUP_ORDER = [
    "Servis Y\u00f6netimi",
    "Stok / Sipari\u015f",
    "Teklif Y\u00f6netimi",
    "Finans",
    "M\u00fc\u015fteri",
    "Personel",
    "Projeler",
    "Sistem",
]

PAGE_PARENTS = {
    62: "Servis Y\u00f6netimi",
    # Servis Yönetimi
    40: "Servis Yönetimi",
    41: "Servis Yönetimi",
    42: "Servis Yönetimi",
    60: "Stok / Sipari\u015f",
    61: "Servis Yönetimi",
    30: "Servis Yönetimi",
    65: "Servis Yönetimi",
    201: "Servis Yönetimi",
    210: "Servis Yönetimi",
    170: "Servis Y\u00f6netimi",
    # Service settings
    140: "Servis Y\u00f6netimi",
    145: "Servis Y\u00f6netimi",
    146: "Servis Y\u00f6netimi",
    147: "Servis Y\u00f6netimi",
    # Stock and purchasing
    50: "Stok / Sipari\u015f",
    51: "Stok / Sipari\u015f",
    66: "Stok / Sipari\u015f",
    250: "Stok / Sipari\u015f",
    300: "Stok / Sipari\u015f",
    # Offers
    150: "Teklif Y\u00f6netimi",
    313: "Teklif Y\u00f6netimi",
    314: "Teklif Y\u00f6netimi",
    # Müşteri
    21: "Müşteri",
    25: "Müşteri",
    26: "Müşteri",
    90: "Müşteri",
    120: "Müşteri",
    # Finans
    101: "Finans",
    105: "Finans",
    106: "Finans",
    115: "Finans",
    # Projeler
    200: "Projeler",
    202: "Projeler",
    # Personel
    10: "Personel",
    # Sistem
    160: "Sistem",
    130: "Sistem",
    180: "Sistem",
    70: "Sistem",
    135: "Sistem",
    261: "Sistem",
}
