# Sector presets

PRESETS = {
    "Insaat / Muteahhit": {
        "prj_page_title": "Proje Yonetimi",
        "prj_btn_new": "+ Yeni Proje Ekle",
        "menu_projects": "Projeler",
        "menu_stock": "Stok & Satis",
        "lbl_unit": "Daire / Bagimsiz Bolum",
        "lbl_subcontractor": "Taseron",
        "tab_units": "Daire & Stok",
        "tab_subs": "Taseronlar",
        "lbl_block": "Blok Adi",
        "lbl_floor": "Kat No",
        "lbl_apt_no": "Daire No",
    },
    "Teknik Servis": {
        "prj_page_title": "Servis Yonetimi",
        "prj_btn_new": "+ Yeni Servis Kaydi",
        "menu_projects": "Servisler",
        "menu_stock": "Yedek Parca Stok",
        "lbl_unit": "Cihaz / Urun",
        "lbl_subcontractor": "Dis Servis / Partner",
        "tab_units": "Cihaz Envanteri",
        "tab_subs": "Cozum Ortaklari",
        "lbl_block": "Marka",
        "lbl_floor": "Model",
        "lbl_apt_no": "Seri No",
    },
    "Tekstil / Uretim": {
        "prj_page_title": "Koleksiyon Takibi",
        "prj_btn_new": "+ Yeni Koleksiyon",
        "menu_projects": "Koleksiyonlar",
        "menu_stock": "Kumas & Aksesuar",
        "lbl_unit": "Urun / Model",
        "lbl_subcontractor": "Fason Atolye",
        "tab_units": "Urun Gami",
        "tab_subs": "Atolyeler",
        "lbl_block": "Kategori",
        "lbl_floor": "Sezon",
        "lbl_apt_no": "Model Kodu",
    },
    "Otomotiv": {
        "prj_page_title": "Servis & Arac Yonetimi",
        "prj_btn_new": "+ Yeni Bakim Karti",
        "menu_projects": "Bakim Takibi",
        "menu_stock": "Yedek Parca & Satis",
        "lbl_unit": "Arac",
        "lbl_subcontractor": "Dis Servis / Tedarikci",
        "tab_units": "Araclar",
        "tab_subs": "Servis Ortaklari",
        "lbl_block": "Marka",
        "lbl_floor": "Model",
        "lbl_apt_no": "Plaka",
    },
}
